# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install -y python3-setuptools
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt --quiet

    - name: Install Intel OpenVINO
      run: |
        sudo curl -o GPG-PUB-KEY-INTEL-OPENVINO-2020 https://apt.repos.intel.com/openvino/2020/GPG-PUB-KEY-INTEL-OPENVINO-2020
        sudo apt-key add GPG-PUB-KEY-INTEL-OPENVINO-2020
        sudo echo "deb https://apt.repos.intel.com/openvino/2020 all main" | sudo tee - a /etc/apt/sources.list.d/intel-openvino-2020.list
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends intel-openvino-dev-ubuntu18-2020.2.130

    - name: Export Model
      run: python3 export_model.py

    - name: Create OpenVINO IR
      run: python3 /opt/intel/openvino/deployment_tools/model_optimizer/mo_onnx.py --input_model model_with_unpool.onnx --extension mo_extensions

    - name: Build CPU extensions
      run: |
        source /opt/intel/openvino/bin/setupvars.sh
        export TBB_DIR=/opt/intel/openvino/deployment_tools/inference_engine/external/tbb/cmake/
        cd user_ie_extensions
        mkdir build && cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release && make -j$(nproc --all)

    - name: Run test
      run: |
        source /opt/intel/openvino/bin/setupvars.sh
        python3 compare.py
